apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: observability-worker-pdb
  namespace: chrono-synth
spec:
  maxUnavailable: 0
  selector:
    matchLabels:
      app.kubernetes.io/name: observability-worker
