apiVersion: v1
kind: Service
metadata:
  name: observability-worker
  namespace: chrono-synth
  labels:
    app.kubernetes.io/name: observability-worker
    app.kubernetes.io/component: observability
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: observability-worker
  ports:
    - name: http
      port: 3100
      targetPort: http
      protocol: TCP
