apiVersion: v1
kind: Secret
metadata:
  name: postgres-secrets
  namespace: chrono-synth
  labels:
    app.kubernetes.io/name: postgres
    app.kubernetes.io/component: database
type: Opaque
stringData:
  POSTGRES_PASSWORD: "CHANGE_ME_USE_openssl_rand_hex_16"
